// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophkeeper/creds_core.go

// Package mock_gophkeeper is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	storage "github.com/Alena-Kurushkina/gophkeeper/internal/storage"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockCredentialer is a mock of Credentialer interface.
type MockCredentialer struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialerMockRecorder
}

// MockCredentialerMockRecorder is the mock recorder for MockCredentialer.
type MockCredentialerMockRecorder struct {
	mock *MockCredentialer
}

// NewMockCredentialer creates a new mock instance.
func NewMockCredentialer(ctrl *gomock.Controller) *MockCredentialer {
	mock := &MockCredentialer{ctrl: ctrl}
	mock.recorder = &MockCredentialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialer) EXPECT() *MockCredentialerMockRecorder {
	return m.recorder
}

// GetUserCredentials mocks base method.
func (m *MockCredentialer) GetUserCredentials(ctx context.Context, userID primitive.Binary) ([]*storage.CredentialsDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentials", ctx, userID)
	ret0, _ := ret[0].([]*storage.CredentialsDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredentials indicates an expected call of GetUserCredentials.
func (mr *MockCredentialerMockRecorder) GetUserCredentials(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentials", reflect.TypeOf((*MockCredentialer)(nil).GetUserCredentials), ctx, userID)
}

// SaveUserCredentials mocks base method.
func (m *MockCredentialer) SaveUserCredentials(ctx context.Context, userID primitive.Binary, encrypted []byte, metaInfo, marking string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserCredentials", ctx, userID, encrypted, metaInfo, marking)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserCredentials indicates an expected call of SaveUserCredentials.
func (mr *MockCredentialerMockRecorder) SaveUserCredentials(ctx, userID, encrypted, metaInfo, marking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserCredentials", reflect.TypeOf((*MockCredentialer)(nil).SaveUserCredentials), ctx, userID, encrypted, metaInfo, marking)
}
