// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophkeeper/core.go

// Package mock_gophkeeper is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	storage "github.com/Alena-Kurushkina/gophkeeper/internal/storage"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gridfs "go.mongodb.org/mongo-driver/mongo/gridfs"
)

// MockStorager is a mock of Storager interface.
type MockStorager struct {
	ctrl     *gomock.Controller
	recorder *MockStoragerMockRecorder
}

// MockStoragerMockRecorder is the mock recorder for MockStorager.
type MockStoragerMockRecorder struct {
	mock *MockStorager
}

// NewMockStorager creates a new mock instance.
func NewMockStorager(ctrl *gomock.Controller) *MockStorager {
	mock := &MockStorager{ctrl: ctrl}
	mock.recorder = &MockStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorager) EXPECT() *MockStoragerMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockStorager) AddUser(ctx context.Context, binaryUUID primitive.Binary, login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, binaryUUID, login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockStoragerMockRecorder) AddUser(ctx, binaryUUID, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockStorager)(nil).AddUser), ctx, binaryUUID, login, password)
}

// CreateDownloadStream mocks base method.
func (m *MockStorager) CreateDownloadStream(fileID primitive.ObjectID) (*gridfs.DownloadStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDownloadStream", fileID)
	ret0, _ := ret[0].(*gridfs.DownloadStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDownloadStream indicates an expected call of CreateDownloadStream.
func (mr *MockStoragerMockRecorder) CreateDownloadStream(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDownloadStream", reflect.TypeOf((*MockStorager)(nil).CreateDownloadStream), fileID)
}

// CreateGridFSStream mocks base method.
func (m *MockStorager) CreateGridFSStream(userID, filename, metainfo string, size int64) (*gridfs.UploadStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGridFSStream", userID, filename, metainfo, size)
	ret0, _ := ret[0].(*gridfs.UploadStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGridFSStream indicates an expected call of CreateGridFSStream.
func (mr *MockStoragerMockRecorder) CreateGridFSStream(userID, filename, metainfo, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGridFSStream", reflect.TypeOf((*MockStorager)(nil).CreateGridFSStream), userID, filename, metainfo, size)
}

// GetFileMetadata mocks base method.
func (m *MockStorager) GetFileMetadata(ctx context.Context, userID, filename string) (*storage.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileMetadata", ctx, userID, filename)
	ret0, _ := ret[0].(*storage.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileMetadata indicates an expected call of GetFileMetadata.
func (mr *MockStoragerMockRecorder) GetFileMetadata(ctx, userID, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileMetadata", reflect.TypeOf((*MockStorager)(nil).GetFileMetadata), ctx, userID, filename)
}

// GetUserCredentials mocks base method.
func (m *MockStorager) GetUserCredentials(ctx context.Context, userID primitive.Binary) ([]storage.CredentialsDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentials", ctx, userID)
	ret0, _ := ret[0].([]storage.CredentialsDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredentials indicates an expected call of GetUserCredentials.
func (mr *MockStoragerMockRecorder) GetUserCredentials(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentials", reflect.TypeOf((*MockStorager)(nil).GetUserCredentials), ctx, userID)
}

// GetUserPassword mocks base method.
func (m *MockStorager) GetUserPassword(ctx context.Context, login string) (*storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPassword", ctx, login)
	ret0, _ := ret[0].(*storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPassword indicates an expected call of GetUserPassword.
func (mr *MockStoragerMockRecorder) GetUserPassword(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPassword", reflect.TypeOf((*MockStorager)(nil).GetUserPassword), ctx, login)
}

// SaveUserCredentials mocks base method.
func (m *MockStorager) SaveUserCredentials(ctx context.Context, userID primitive.Binary, encrypted []byte, metaInfo, marking string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserCredentials", ctx, userID, encrypted, metaInfo, marking)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserCredentials indicates an expected call of SaveUserCredentials.
func (mr *MockStoragerMockRecorder) SaveUserCredentials(ctx, userID, encrypted, metaInfo, marking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserCredentials", reflect.TypeOf((*MockStorager)(nil).SaveUserCredentials), ctx, userID, encrypted, metaInfo, marking)
}

// Shutdown mocks base method.
func (m *MockStorager) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockStoragerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockStorager)(nil).Shutdown), ctx)
}
