// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophkeeper/core.go

// Package mock_gophkeeper is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShutdowner is a mock of Shutdowner interface.
type MockShutdowner struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownerMockRecorder
}

// MockShutdownerMockRecorder is the mock recorder for MockShutdowner.
type MockShutdownerMockRecorder struct {
	mock *MockShutdowner
}

// NewMockShutdowner creates a new mock instance.
func NewMockShutdowner(ctrl *gomock.Controller) *MockShutdowner {
	mock := &MockShutdowner{ctrl: ctrl}
	mock.recorder = &MockShutdownerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdowner) EXPECT() *MockShutdownerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockShutdowner) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockShutdownerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockShutdowner)(nil).Shutdown), ctx)
}
