// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophkeeper/user_core.go

// Package mock_gophkeeper is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	storage "github.com/Alena-Kurushkina/gophkeeper/internal/storage"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockUserer is a mock of Userer interface.
type MockUserer struct {
	ctrl     *gomock.Controller
	recorder *MockUsererMockRecorder
}

// MockUsererMockRecorder is the mock recorder for MockUserer.
type MockUsererMockRecorder struct {
	mock *MockUserer
}

// NewMockUserer creates a new mock instance.
func NewMockUserer(ctrl *gomock.Controller) *MockUserer {
	mock := &MockUserer{ctrl: ctrl}
	mock.recorder = &MockUsererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserer) EXPECT() *MockUsererMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserer) AddUser(ctx context.Context, binaryUUID primitive.Binary, login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, binaryUUID, login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUsererMockRecorder) AddUser(ctx, binaryUUID, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserer)(nil).AddUser), ctx, binaryUUID, login, password)
}

// GetUserPassword mocks base method.
func (m *MockUserer) GetUserPassword(ctx context.Context, login string) (*storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPassword", ctx, login)
	ret0, _ := ret[0].(*storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPassword indicates an expected call of GetUserPassword.
func (mr *MockUsererMockRecorder) GetUserPassword(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPassword", reflect.TypeOf((*MockUserer)(nil).GetUserPassword), ctx, login)
}
